### ISSUE TITLE
Data Extractor Issues

### ISSUE THREAD

**Issue by Gurupra** [unislink/dataextractor#8]
Please fix the below error:

Traceback (most recent call last):
  File "dataExtractor.py", line 119, in <module>
    dataFrames = defc.dataFrameCreator(Connection,sqlQuery)
  File "utils\dataextractorfunctions.py", line 167, in dataFrameCreator
    dataFrame = read_sql(sqlQuery, connection, chunksize=chunkSize)
  File "Python\Python35\lib\site-packages\pandas\io\sql.py", line 399, in read_sql
    chunksize=chunksize)
  File "Python\Python35\lib\site-packages\pandas\io\sql.py", line 1436, in read_query
    cursor = self.execute(*args)
  File "Python\Python35\lib\site-packages\pandas\io\sql.py", line 1396, in execute
    cur = self.con.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'

**Comment by Gurupra** [comment]
Not needed for now
